//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report_Tracker_Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadFile
    {
        public int FileId { get; set; }
        public int BlogId { get; set; }
        public string FileName { get; set; }
        public int FileSize { get; set; }
        public string ContentType { get; set; }
        public string Extension { get; set; }
        public byte[] Content { get; set; }
    }
}
